### ISSUE TITLE
Not working with compose 1.4

### ISSUE THREAD

**Issue by rohitjakhar** [hi-manshu/Pluck#30]
I got crash when use Pluck with permission
here is stack trace

java.lang.NoSuchMethodError: No static method Scaffold-zOzJ79U(Landroidx/compose/ui/Modifier;Lkotlin/jvm/functions/Function2;Lkotlin/jvm/functions/Function2;Lkotlin/jvm/functions/Function2;Lkotlin/jvm/functions/Function2;IJJLkotlin/jvm/functions/Function3;Landroidx/compose/runtime/Composer;II)V in class Landroidx/compose/material3/ScaffoldKt; or its super classes (declaration of 'androidx.compose.material3.ScaffoldKt' appears in /data/app/~~zsV8t1-rFJuDKJsPlpQT2A==/com.eventgo.app-HnRnepwOmgQ393YaqlSIOA==/base.apk)
                                                                                                    	at com.himanshoe.pluck.ui.permission.PermissionKt$Permission$1.invoke(Permission.kt:75)
                                                                                                    	at com.himanshoe.pluck.ui.permission.PermissionKt$Permission$1.invoke(Permission.kt:74)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at com.google.accompanist.permissions.PermissionsRequiredKt.PermissionsRequired(PermissionsRequired.kt:97)
                                                                                                    	at com.himanshoe.pluck.ui.permission.PermissionKt.Permission(Permission.kt:72)
                                                                                                    	at com.eventgo.app.ui.screen.create_event.CreateEventScreenKt$CreateEventScreen$3$1.invoke(CreateEventScreen.kt:137)
                                                                                                    	at com.eventgo.app.ui.screen.create_event.CreateEventScreenKt$CreateEventScreen$3$1.invoke(CreateEventScreen.kt:135)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:132)
                                                                                                    	at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:114)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
                                                                                                    	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
                                                                                                    	at androidx.compose.material3.SurfaceKt.Surface-T9BRK9s(Surface.kt:111)

**Comment by rohitjakhar** [comment]
This crash happing again and again and not give proper reason.

**Comment by joserodpt** [comment]
Same for me

**Comment by aliCashGate** [comment]
@hi-manshu Still facing this issue. Can you please guide us to find the solution for it?
